apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atoinium-operator-role
rules:
  - apiGroups: [""]
    resources:
      ["namespaces", "secrets", "events", "serviceaccounts", "services"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["atoiniumhpcgroup.thera.atonixcorp.com"]
    resources: ["nginxes", "nginxes/status", "nginxes/finalizers"]
    verbs: ["*"]
