apiVersion: apps/v1
kind: Deployment
metadata:
  name: atoinium
  namespace: atoiniumhpc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atoinium
  template:
    metadata:
      labels:
        app: atoinium
    spec:
      containers:
        - name: atoinium-container
          image: ofidohubvm/atoinium_atoiniumhpc:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: github-regcred
        
