version: '3'
services:
  backend:
    build:
      context: ./atoiniumhpc
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./atoiniumhpc:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./atoiniumwebapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./atoiniumwebapp:/app
    depends_on:
      - backend

  atoiniumhpc:
    build:
      context: ./atoiniumhpc
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Change the host port to 8081
    volumes:
      - ./data:/data  # Mount the ./data directory on the host to /data in the container

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: atoinium_db
      POSTGRES_USER: guxegdsa
      POSTGRES_PASSWORD: F?*RTAGl6
    ports:
      - "5433:5432"

volumes:
  postgres_data: