version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build:
    executor: docker-executor
    environment:
      IMAGE_TAG: docker/scout-demo-service:latest
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh

      - run:
          name: Build Docker Image
          command: |
            docker build -t ofidohubvm/atoinium_atoiniumhpc:latest .

      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u ofidohubvm --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push ofidohubvm/atoinium_atoiniumhpc:latest

      - run:
          name: Install Docker Scout
          command: |
            curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      - run:
          name: Scan Docker Image with Docker Scout
          command: |
            docker scout cves ofidohubvm/atoinium_atoiniumhpc:latest

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
