apiVersion: apps/v1
kind: Deployment
metadata:
  name: atoinium-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atoinium
  template:
    metadata:
      labels:
        app: atoinium
    spec:
      containers:
        - name: atoiniumcontainer
          image: ofidohubvm/atoinium:latest # Replace with your Docker image
          ports:
            - containerPort: 8000 # Replace with the port your application listens on
