apiVersion: v1
kind: Service
metadata:
  name: atoinium-service
  namespace: default
spec:
  selector:
    app: atoinium
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
